### PR TITLE
Add release notes for v0.11.0

### PR DESCRIPTION
**Pull request by glestaris**

### CODE REVIEW

**Comment by glestaris** [comment]
I will do the merging a bit later today. I just want to finish accepting some stories and validate the component versions section.

**Comment by seviet** [comment]
@glestaris do you want us to hold off on merging this into master then?

**Comment by glestaris** [comment]
Hey @seviet, yes I was waiting to finish some acceptance and have someone take a second look.

We are good to go now.

**Comment by animatedmax** [comment]
Thank you, @glestaris

**Pull request merged**
